server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serverUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    #此配置建议只试用开发和测试环境 驱逐下线的服务，间隔,5秒，默认是60
    eviction-interval-timer-in-ms: 5000